INC_DIRS+=				$(MP3_DIR)
INC_DIRS+=				$(MP3_DIR)/helix_mp3
INC_DIRS+=				$(MP3_DIR)/helix_mp3/pub
INC_DIRS+=				$(MP3_DIR)/helix_mp3/real

SRC_DIRS+=				$(MP3_DIR)
SRC_DIRS+=				$(MP3_DIR)/helix_mp3
SRC_DIRS+=				$(MP3_DIR)/helix_mp3/real
SRC_DIRS+=				$(MP3_DIR)/alarms