INC_DIRS+=$(FAT_DIR)
INC_DIRS+=$(FAT_DIR)/fatfs
INC_DIRS+=$(FAT_DIR)/fatfs/lo_level

INC_DIRS+=$(FAT_DIR)/cmsis_lib/include

SRC_DIRS+=$(FAT_DIR)
SRC_DIRS+=$(FAT_DIR)/fatfs
SRC_DIRS+=$(FAT_DIR)/fatfs/lo_level

SRC_DIRS+=$(FAT_DIR)/cmsis_lib/source