INC_DIRS+= $(USB_DIR)/inc
INC_DIRS+= $(USB_DIR)/STM32_USB_Device_Library/Core/inc
INC_DIRS+= $(USB_DIR)/STM32_USB_Device_Library/Class/hid_custom/inc
INC_DIRS+= $(USB_DIR)/STM32_USB_OTG_Driver/inc

SRC_DIRS+= $(USB_DIR)/src
SRC_DIRS+= $(USB_DIR)/STM32_USB_Device_Library/Core/src
SRC_DIRS+= $(USB_DIR)/STM32_USB_Device_Library/Class/hid_custom/src
SRC_DIRS+= $(USB_DIR)/STM32_USB_OTG_Driver/src